name: tbmobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.0
  email_validator: ^2.1.0
  google_fonts: ^6.1.0
  animate_do: ^3.3.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
